---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _sections
  label: Sections
  create: all
  match: "**/*"
  templates:
  - section
- type: directory
  path: _artists
  label: Artists
  create: all
  match: "**/*"
  templates:
  - artist
- type: directory
  path: _releases
  label: Releases
  create: all
  match: "**/*"
  - release
- type: jekyll-posts
  label: Posts
  create: all
  hidden: true
- type: jekyll-pages
  label: Pages
  create: all
  hidden: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
